// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
"use strict";

var $$String = require("bs-platform/lib/js/string.js");

function finder(day) {
  switch (day) {
    case /* Success */ 0:
      return "Hello World";
    case /* Error */ 1:
      return "Another Error , yikes";
    case /* Dead */ 2:
      return "Wel go to bead";
  }
}

var newFinder = $$String.uppercase_ascii($$String.lowercase_ascii(finder(/* Error */ 1)));

console.log(newFinder);

var data = /* Error */ 1;

exports.data = data;
exports.finder = finder;
exports.newFinder = newFinder;
/* newFinder Not a pure module */
